# Generated by Django 3.2.14 on 2022-07-08 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyRoomBookings',
        ),
    ]
