# Generated by Django 4.0.6 on 2022-07-08 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyRoomBookings',
        ),
    ]
