# Generated by Django 4.0.6 on 2022-07-08 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_delete_dailyroombookings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodsmodel',
            name='food_type',
            field=models.CharField(max_length=200),
        ),
    ]
